### ISSUE TITLE
Unified fields list

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#188]
Do we need to have a unified list of fields with some metadata about them?
In this way all the components referring to the fields will be consistent. Also we can expose it to the end users to call our services with the known fields.

This can be a web service or a page on github. If it's a web service it can be populated automatically and in case of changes in the fields (naming/indexing/storing) it can be reflected accordingly.

The structure can be a json format like:
```json
[{
	"id":"latitude",
	"dwcName": "decimalLatitude",
	"descriptiveName": "Latitude - original",
	"solr": {
		"fieldName": "latitude",
		"processedFieldName": "latitude_processed",
		"sensitiveFieldName": "sensitive_latitude",
		"stored": true,
		"indexed": true
	},
	"db": {
		"fieldName": "decimalLatitude",
		"processedFieldName": "decimalLatitude.processed",
		"sensitiveFieldName": "sensitive.decimalLatitude"
	},
	"sensitivityCheckNeeded": "true",
	"isProcessed": "false",
	"dataType": "string"
}]
```

**Comment by adam-collins** [comment]
The current unified field info ws is http://biocache.ala.org.au/ws/index/fields

A csv version is included in downloads.

A description of the various field names, mappings between sources and descriptions: https://github.com/AtlasOfLivingAustralia/biocache-service/wiki/index-fields

Cassandra only fields are absent from the above ws. They could be included as stored:false and indexed:false.

**Comment by nielsklazenga** [comment]
I am not sure if I am talking about the same thing as Mahmoud, but, as a user, I would be very interested in a unified field list that includes fields that are in use anywhere in ALA, not just the BioCache, and which ensures that everywhere in ALA the same thing is given the same name or, if different, that the names can be reconciled. To me, a list of fields in the BioCache is not a unified field list, no matter how good and useful that list is.

Also, I don't want to hijack this issue, but since Adam mentioned it, I have encountered some fields (for example cl1049, establishment_means) that are marked as 'stored:true' and 'index:true', but for which I cannot retrieve the data. I thought that 'stored:true' meant that it is stored in the SOLR index, so I should be able to downlaod it. Am I wrong?

**Comment by adam-collins** [comment]
This issue is for biocache Cassandra and SOLR fields.

It would be useful to return multivalue:true for multivalued SOLR fields such as establishment_means. Multivalued fields cannot be used everywhere.

**Comment by sadeghim** [comment]
> Cassandra only fields are absent from the above ws. They could be included as stored:false and indexed:false.

I can work on this part.

**Comment by M-Nicholls** [comment]
Changes to some of field labels used, they could be more intuitive:

“Name” change to “indexFieldName”
“downloadName” change to “databaseFieldName”
“description” change to “facetUILabel” – is this used anywhere else?
“downloadDescription” change to "downloadFieldName"
 “info” – where is this text used?

and Add:
“dwcClass” – which Darwin class group the field belongs to
“basicIndexExport” – boolean, whether the field is in the preset basic index export fields
“extendedIndexExport” - boolean, whether the field is in the preset extended index export fields

to be populated by additional information in https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/webapp/WEB-INF/messages.properties or a lookup on the DwC spec if possible
