### ISSUE TITLE
ALA legacy download issues

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#211]
New ALA legacy download includes extra fields compered to the current download:
- Subspecies - matched
- Coordinate Precision
- State - parsed
- Local Government Areas
- Minimum Elevation In Metres
- Maximum Elevation In Metres
- Minimum Depth In Meters
- Maximum Depth In Meters
- individual Count
- Day - parsed
- Event Time - parsed
- Preparations
- Information withheld during processing
- Data Generalised during processing
- Species habitats
- Location Quality
- record _ number

Remove the above from the ALA legacy download.

current download has extra QA fields:
- Supplied country not recognised
- Kingdom not recognised
- unrecognised Occurrence Status
- Type status not recognised
- Unrecognized geodetic datum

Add the above to the ALA legacy download.

**Comment by nickdos** [comment]
Assigning to @adam-collins - this should be implemented in biocache-service as 3rd party users will be expecting legacy format to provide the same output as current download.

**Comment by nickdos** [comment]
Did a diff on the headers.csv from both downloads (old vs new):

```diff
1	1	  Column name
2	2	  Record ID
3	3	  Catalog Number
4	4	  Match Taxon Concept GUID
5	5	  Scientific Name
6	6	  Vernacular Name
7	7	  Matched Scientific Name
8	8	  Taxon Rank - matched
9	9	  Vernacular Name - matched
10	10	  Kingdom - matched
11	11	  Phylum - matched
12	12	  Class - matched
13	13	  Order - matched
14	14	  Family - matched
15	15	  Genus - matched
16	16	  Species - matched
17	+ Subspecies - matched
17	18	  Institution Code
18	19	  Collection Code
19	20	  locality
20	21	  Latitude - original
21	22	  Longitude - original
22	23	  geodetic Datum
23	24	  Latitude - processed
24	25	  Longitude - processed
26	+ Coordinate Precision
25	27	  Coordinate Uncertainty in Metres - parsed
26	28	  Country - parsed
29	+ IBRA Region - parsed
30	+ IMCRA Region - parsed
27	31	  State - parsed
28	32	  Local Government Areas
33	+ Minimum Elevation In Metres
34	+ Maximum Elevation In Metres
35	+ Minimum Depth In Meters
36	+ Maximum Depth In Meters
37	+ individual Count
29	38	  Collector
30	39	  Year - parsed
31	40	  Month - parsed
41	+ Day - parsed
32	42	  Event Date - parsed
43	+ Event Time - parsed
33	44	  Basis Of Record - original
34	45	  Basis Of Record - processed
35	46	  Sex
47	+ Preparations
48	+ Information withheld during processing
49	+ Data Generalised during processing
50	+ Species habitats
36	51	  Outlier for layer
37	52	  Taxon identification issue
53	+ Location Quality
38	54	  Data Resource ID
39	55	  Data Resource Name
40		- Altitude value non-numeric
41		- Occurrence status assumed to be present
42		- Coordinate precision not valid
43		- Country inferred from coordinates
44		- Coordinates converted to WGS84
45		- First of the month
46		- Geodetic datum assumed WGS84
47		- Incomplete collection date
48		- Invalid collection date
49		- Name not in national checklists
50		- Name not recognised
51		- Resource taxonomic scope mismatch
56	+ record _ number
```

**Comment by adam-collins** [comment]
The offline download was redirecting to Cassandra instead of SOLR for the data because there are some out of date fields in the default field listing. occurrences/download ws did match the offline ws but that is not in use. Also, need to use the same qa param in both download requests.

biocache-store index fields changes 
subspecies_name subspecies.p 
geospatiallyKosher geospatial_kosher

biocache-service default download field changes 
coordinatePrecision remove
ibra.p cl1048
imcra.p cl21
minimumElevationInMeters minimumElevationInMeters.p
maximumElevationInMeters maximumElevationInMeters.p
minimumDepthInMeters minimumDepthInMeters.p
maximumDepthInMeters maximumDepthInMeters.p
individualCount remove
day.p remove
eventTime remove
preparations remove
informationWithheld.p remove
dataGeneralizations.p remove
speciesHabitats.p remove
