### ISSUE TITLE
issues with AVH load data mapping

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#399]
from support ticket: https://support.ehelp.edu.au/a/tickets/18411

Hi
 
We’ve found some issues with the AVH DwC exports from AVH as per my email below and Anne’s response. In particular the mapping of ‘Locality’ and ‘Habitat’ fields for the DwC export.
 
Regards
Frank
 
---------------------------------
 
Hi Frank
 
I can see that we are delivering this to the ALA and you are right, it is not being mapped into the DwC output. In terms of the specific attributes

    we supply ‘Locality’ in Locality as does BRI. We don’t currently supply verbatim Locality (but it will be available in the CMS) so it looks like the ALA is mapping this data to occurrenceRemarks, although Locality is a DwC term.
    Habitat is being supplied but is not mapped to the DwC output

 
Cheers Anne
 
--------------------------------
 
Hi Anne
 
I’ve downloaded Darwin Core data from AVH (http://avh.ala.org.au/ ) for ‘Brass, L.J.’ records at CANB, CNS and BRI this morning to compare duplicates held between the three institutions, but noticed that there are some problems. The ALA legacy download has the Locality field but in the Darwin Core download:
·         ‘Locality’ field is blank
·         ‘VerbatimLocality’ has a few fields populated
·         ‘OccurrenceRemarks’ field which holds the Location and Notes data from BRI, is missing the Locality data for CANB and CNS.  
·         ‘Habitat’ is also blank.
 
The CANB and CNS data is in AVH, so it appears to be an ALA issue with Darwin Core exports? I just wanted to check with you before sending to ALA?
 
Eg. CANB 24008 and BRI AQ0261826 are duplicates of Brass 401
http://avh.ala.org.au/occurrences/8fb11a31-dd13-4651-bb40-f45675cb5fcc
 
Eg. QRS 32676 and BRI AQ0056110 are dups of Brass 33560.
http://avh.ala.org.au/occurrences/3699425a-b5a1-4ad4-b682-b7f0aaed21da
 
Thanks
Frank

**Comment by nielsklazenga** [comment]
I can explain...

The locality and habitat fields in the ALA downloads is not being populated for some reason (probably has something to do with the provided data being replaced in the index by data that is inferred from the latitude and longitude, using Local Government Areas and IRMNMG "Habitat" respectively). This has been an issue for a long time (two years at least) and was again reported by Frank a few months ago.

Australian herbaria have traditionally not separated `locality` and `verbatimLocality`, but since the HISPID review, considering that what is delivered as `locality`  is really `verbatimLocality`, the `locality` that is harvested from ABCD providers has been mapped to and delivered as both `locality` and `verbatimLocality` (see https://github.com/hiscom/avh-biocase/blob/master/wiki/avh_data.wiki#locality; there have been emails on the HISCOM list as well) unless either term is delivered separately in the DwC extension. Therefore, `verbatimLocality` will be there for AVH records that have been loaded in the last two years or so, but not in records that have been loaded before. We need to re-deliver the entire AVH data set to remedy this. Re-harvesting of all AVH data is highly overdue, but will not be prioritised before a review of the AVH harvesting and aggregation has taken place.

So no data load issue here.
