### ISSUE TITLE
Update Victorian Biodiversity Atlas data

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#460]
Last update was 2017. See https://github.com/AtlasOfLivingAustralia/data-management/issues/172

**Comment by peggynewman** [comment]
Firstly an analysis is required to establish the best way forward with VBA. The below links are to shapefiles, and there is probably an opportunity for acquiring Darwin Core at source rather than via data.vic.

Datasets

Flora observations:
High Accuracy flora https://discover.data.vic.gov.au/dataset/victorian-biodiversity-atlas-flora-records-unrestricted-for-sites-with-high-spatial-accuracy
Low accuracy flora https://discover.data.vic.gov.au/dataset/victorian-biodiversity-atlas-flora-records-unrestricted-for-sites-with-moderate-to-low-spatial-
 
Fauna observations:
High Accuracy fauna https://discover.data.vic.gov.au/dataset/victorian-biodiversity-atlas-flora-records-unrestricted-for-sites-with-high-spatial-accuracy
Low accuracy fauna https://discover.data.vic.gov.au/dataset/victorian-biodiversity-atlas-fauna-records-unrestricted-for-sites-with-moderate-to-low-spatial-

These include some of the museum, eBird, Birdlife and herbarium records.

**Comment by peggynewman** [comment]
Created a new issue for this: https://github.com/AtlasOfLivingAustralia/data-management/issues/619. Closing.
