### ISSUE TITLE
Re-load ANIC whole drawer images

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#467]
emails from NF with links and data sheets

info on share drive in data file store - ANIC/images/whole drawer images

**Comment by M-Nicholls** [comment]
NF is getting IM&T to reduce the file size

**Comment by peggynewman** [comment]
These images were previously loaded via a morphbank dataset (dr441), which has been deleted in the license clean up, so the images are now orphaned in the image service. (Discoverable via images, dr441, date loaded 2014)

ANIC would like these reinstated. However, they have created some new and better (smaller size - 13MB rather than 500MB) scans and would like to load them, so this can be created as a new load. The new files that have been produced have the pattern ```<filename>50pcnt_qlty80.jpg```

Will send through an email containing data files and the shared drive location. They would like to load everything in these 3 directories:
1.) Hall_Coleoptera 
2.) Hall_Compactus 
3.) Hall_Lepidoptera

Recommend loading via:
**dr2288** - Australian National Insect Collection Image Library (last load 2016, collectory file upload)
rather than dr130 (Australian National Insect Collection (last load 2019, collectory file upload)), which only contains PreservedSpecimen.
- [ ] dr2288 should also be "added to" dp17.

The images used to appear here: https://specimens.ala.org.au/browse/co13. Setting the right institutionCode and collectionCode will ensure they are. See https://collections.ala.org.au/providerMap/show/1?returnTo=co13

- institutionCode = “CSIRO”
- collectionCode = “ANIC” 
- catalogNumber = field:98001021-1
- scientificName = field:Determination Scientific Name
- Licence = field:Creative Commons (href maybe?)
-- eg. value ```<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/">Creative Commons Attribution-Non Commercial 3.0 Australia License.</a>.```
- Rights holder = field: Copyright (eg. CSIRO)
- basisOfRecord - empty
- geospatial details - empty
 
Contacting the data provider about images in the drive that have no metadata provided.
