### ISSUE TITLE
Update Flickr Harvester

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/data-management#471]
Update Flickr harvester to increase the performance of the data load on ALA by creating the delta including only new and updated records.

**Comment by peggynewman** [comment]
Also note problem with images coming across https://github.com/AtlasOfLivingAustralia/data-management/issues/553

**Comment by peggynewman** [comment]
The Flickr load appears to be broken. Need to understand what to do with this feed given that EOL is no longer functional. MV and BHL have relied on this feed in the past.

**Comment by peggynewman** [comment]
Since pipelines migration, the Flickr data resource needs attention:
* should data be cleaned up and updated?
* should the jenkins load job be migrated? 

There are many blank images ...  faceting on year 2020, no images loaded yet the record in Flickr has images.
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr360

**Comment by peggynewman** [comment]
Investigate whether to set this feed back up again using pre-ingestion. Previous code for loading Flickr data here: https://github.com/AtlasOfLivingAustralia/biocache-store/blob/develop/src/main/scala/au/org/ala/biocache/load/FlickrLoader.scala

**Comment by peggynewman** [comment]
See the discussion about this on the #general slack channel. There's not a lot of enthusiasm for this. I'll leave this in the backlog but we probably won't proceed.
