### ISSUE TITLE
Image specific attribution from sightings not displayed on record details page

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#513]
Issue with ALA sightings load:

https://biocollect.ala.org.au/sightings/bioActivity/index/af6535c1-d31d-463e-a1f9-cef197f752ce?returnTo=%2Fsightings%2FbioActivity%2FmyProjectRecords%2Fnull

mouse-over or click on images in record linked above show image attribution as "Attribution: Mickayla Heinemann - Lockyer Community Action Inc." once loaded into the ALA the image attribution is not shown (https://biocache.ala.org.au/occurrences/2588ad30-1282-4c46-9c0f-78b850a3bf73) on the record details page

and the images record (https://images.ala.org.au/image/8062033b-922e-43e5-8bdf-cdad3021575e) shows the creator as "Gordon Claridge" without any record of the attribution from the sightings record.

**Comment by ansell** [comment]
The two images that are currently linked to from that biocache record look correct:

https://images.ala.org.au/image/details?imageId=33b2d3aa-e1bc-43d7-ac98-eea7de8f12ff

https://images.ala.org.au/image/details?imageId=ce1addcc-acd9-474a-9c27-edc8e1df34da

The image linked to above is not currently linked to from that biocache record but it still exists:

https://images.ala.org.au/image/8062033b-922e-43e5-8bdf-cdad3021575e

Was there already work done on this issue (perhaps it is a duplicate issue?)

The remaining issue of not displaying the Creator/Rights Holder seems to be in the biocache-hubs UI. A separate issue would need to be created for that in the biocache-hubs issue tracker, rather than the data-management tracker.

**Comment by timhicks-ala** [comment]
I think I've just ended up opening that ticket today: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/561

Was one already opened in biocache-hubs?

**Comment by patkyn** [comment]
The 2  images are correctly linked now in the dwca 
![image](https://user-images.githubusercontent.com/1606595/133174424-73156f92-f140-4eb7-810c-98c80f9b5ec9.png)

However, it is not appearing for the occurrence record until this issue is fixed: https://github.com/AtlasOfLivingAustralia/biocollect/issues/1343

**Comment by patkyn** [comment]
The correct images are now linked to the biocache record. https://biocache.ala.org.au/occurrences/2588ad30-1282-4c46-9c0f-78b850a3bf73

![image](https://user-images.githubusercontent.com/1606595/139603670-37b07ca8-4f91-408b-9735-7044f6dc239b.png)

https://images.ala.org.au/image/details?imageId=ce1addcc-acd9-474a-9c27-edc8e1df34da
