### ISSUE TITLE
iNaturalist Data load : updated identification not coming through to biocache

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#555]
At the time of writing this record in biocache has status "needs id"
https://biocache.ala.org.au/occurrences/130257c1-30d1-4a80-988d-ebddb0c6e779
Scientific Name:  Theretra radiosa
Date identified: 2020-01-18

But in iNaturalist, 8 days ago it reached "research grade" with some new identifications.
https://www.inaturalist.org/observations/37706379
Scientific Name: Theretra queenslandi
Date identified: 8 days ago from 2020-01-29

We need these changes to come through. Are updated identifications making it through the daily API?

**Comment by ansell** [comment]
The last full weekly refresh was yesterday after the reindex job ran. Todays reindex job failed due to the other issues with solr this morning. Could we possibly wait for 14 days for the status to change on existing records rather than opening issues on 8 day timeframes?

**Comment by ansell** [comment]
Removing the "bug" tag from this until tomorrow at the earliest to verify it.

**Comment by peggynewman** [comment]
Because there is a nightly reindex I would have thought 8 days was an outside estimate. iNaturalist records should be updated weekly at the least. I'll check tomorrow though. Happy for you to remove the bug tag till the index update.

**Comment by ansell** [comment]
The weekly update seemed to work to update Cassandra yesterday morning. Those changes would have been then become active this morning in Solr if the reindex this morning had not failed due to the widespread biocache/solr/zookeeper issues when it ran.

Intermittent failures like this morning are why Mahmoud and I try to manage expectations by adding in buffer time to the best case to allow for variances. 14 days may be too long, but at least 10 days is necessary with our current schedule to avoid having issues created like this when the schedule has one hiccough.

**Comment by peggynewman** [comment]
Other records to test that have come through https://support.ehelp.edu.au/a/tickets/73275 

https://biocache.ala.org.au/occurrences/4d9aaf43-b563-4101-be7e-d92868a914a2
https://www.inaturalist.org/observations/37777189

https://biocache.ala.org.au/occurrences/6a29df87-328c-45ab-a6da-02dff91c9173
https://www.inaturalist.org/observations/37972986

https://biocache.ala.org.au/occurrences/e44198fd-dde7-42fc-ad06-074de68cc6c2
https://www.inaturalist.org/observations/37981790
