### ISSUE TITLE
Data load : ANWC Fix load + migrate off ala-dury

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#581]
- [ ] After creation, add this issue to the Data Management project board https://github.com/orgs/AtlasOfLivingAustralia/projects/9

- [ ] Map dataset to Darwin Core Terms if necessary http://rs.tdwg.org/dwc/terms/
- [ ] Upload the dataset to collections.ala.org.au
- [ ] Load/sample/process dataset http://aws-scjenkins.ala:9193/job/Parameterised%20Load%20Sample%20Process/ 
- [ ] Note the statistics for total and new records from the end of the log file for the load by pasting the relevant lines here:
```
[Log entries..... ]
```
- [ ] Wait for next complete reindex
- [ ] Check that the number of records accessible match the loaded numbers using https://biocache.ala.org.au/occurrence/search?q=data_resource_uid:drNNN
- [ ] Ask the data provider to review the new records using the same URL

**Comment by peggynewman** [comment]
https://support.ehelp.edu.au/a/tickets/38166. Load has been busted for a while. Possibly a build up of a number of files.

**Comment by ansell** [comment]
There are no deltas for ANWC, just two separate input files that need to be merged together into a Darwin Core Archive before loading.

**Comment by patkyn** [comment]
Latest update, I tried packaging a darwin core archive with X00105 occurrence record and it's related sound file and uploaded to collectory, this time with identifier in multimedia extension pointing to the actual file name itself like this: 
![image](https://user-images.githubusercontent.com/1606595/84451204-b4b3ac80-ac95-11ea-87d0-d17d50aa407d.png)

Then I triggered the  Parameterised Load Sample Process job for dr341. The load job seems this time has picked up the sound media file and because it's already existed in image service, it doesn't recreate another copy.

**Comment by peggynewman** [comment]
So in the media file does it read the identifier or the associatedMedia field to get the file?

**Comment by patkyn** [comment]
It's picking up the Identifier not associateMedia. I swapped the values around.

**Comment by peggynewman** [comment]
Rock on, well done.

**Comment by peggynewman** [comment]
I'll write to Margaret and let her know it's done.

**Comment by patkyn** [comment]
Script which generates the dwca file is now correctly populating the multimedia extension identifier field with the multimedia file name. The sounds for the occurrence records is now fixed.
