### ISSUE TITLE
Clean up Geelong Field Naturalists Club data resources 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#645]
There are at least 3 data resources for Geelong Field Naturalists Club:
https://collections.ala.org.au/public/showDataResource/dr11900
https://collections.ala.org.au/public/show/dr10631
https://collections.ala.org.au/public/show/dr573

These should be consolidated into one single data resource. Check the tickets in the support queue from them. This is one:
https://support.ehelp.edu.au/a/tickets/76129

The collectory entries will have to be updated/deleted, and data will have to be prepared and reloaded.

**Comment by peggynewman** [comment]
The Data provider wants to keep dr10631
- [ ] Copy the description, website fields from dr573 to dr10631
- [ ] Delete dr573

They want to move the data from dr11900 into dr10631

- [ ] Review the source dataset for dr11900 in the connection parameters. Important fields:
- Data URLs field
- DwCtermsthatuniquelyidentifyarecord: occurrenceID

- [ ] Review the target dataset  dr1063. What is the unique key in the connection parameters? Is it the same?
- [ ] work out how to make the unique identifiers consistent and that there will be **no duplicates**
- [ ] get help to work out how to remap the rowkey/uuid in Cassandra for the data in dr11900.
load the source datafile from dr11900 into dr1063 by:
- [ ] changing the connection parameters in dr1063
- [ ] create a new Parameterised Load Sample Process build in Jenkins with dr1063 parameter and build
- [ ]  check for records after next index run

- [ ] Delete records from dr11900 using the Delete Query in Jenkins (ask for help)

**Comment by zalicedc** [comment]
Website of dr573 http://home.vicnet.net.au/~gfnc/ not found (The requested URL was not found on this server.)

**Comment by peggynewman** [comment]
To merge the data into the target DR:
- [ ] Download the file from dr11900 
- [ ] correct the spelling in occurrenceID field header

- [ ] append each occurrenceID value with prefix "butterfly-"
- [ ] upload csv file into dr10631 (ensure that the connection parameters unique key is set to occurrenceID

**Comment by zalicedc** [comment]
aws-bstore-4b 2021-02-12 13:21:01,904 INFO : [DataLoader] - There are 1017 records in the file. The number of NEW records: 1016
aws-bstore-4b 2021-02-12 13:21:01,904 INFO : [DataLoader] - Load finished for dr10631.csv
aws-bstore-4b 2021-02-12 13:21:02,056 INFO : [DataLoader] - Registry response code: 200
aws-bstore-4b 2021-02-12 13:21:02,056 INFO : [Loader] - Completed loading resource: dr10631. Completed in 67.972seconds (1.1328666 minutes)
Finished: SUCCESS

**Comment by zalicedc** [comment]
Running on Jenkins in /var/lib/jenkins/workspace/Delete Records By Query
[Pipeline] {
[Pipeline] echo
Skipped stopping VMs
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

1015 Records are deleted.

**Comment by patkyn** [comment]
There were 1016 records originally from dr11900.

Due to the DeleteByQuery solr issue, it doesn't wipe out the entire dr11900 
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr11900 still showing 1 record today
![image](https://user-images.githubusercontent.com/1606595/108003658-8cabf280-7047-11eb-9353-38f2983be6bf.png)


The collectory dataresource https://collections.ala.org.au/public/show/dr11900 should be deleted as well after all the biocache records are deleted 

Some issues with the images in dr10631.
After some investigation, it seems that the links flickr image links are not the actual image links. This has been a known issue, biocache had not been able to ingest links that are not the actual image links. We had encountered this issue previously. 

For eg: https://www.flickr.com/photos/possypics/23509846696/ if we look into view-source:https://www.flickr.com/photos/possypics/23509846696/ , the actual image link is in https://live.staticflickr.com/5678/23509846696_2c1c4801fe_b.jpg as shown below

![image](https://user-images.githubusercontent.com/1606595/108004007-a39f1480-7048-11eb-80d8-6ff812596612.png)

**Comment by zalicedc** [comment]
The Jenkins delete job has been re-executed that has successfully deleted the 1 remaining record from dr11900. 

The collectory dataresource https://collections.ala.org.au/public/show/dr11900 has been successfully removed after all records deleted.
