### ISSUE TITLE
dr2153 - NZVH - migrate load to pipelines jenkins

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#688]
ran fridays weekly 1pm

**Comment by nielsklazenga** [comment]
This job mostly consists of a bash script that can probably be copied straight over to the new Jenkins server. However, the bash script contains the credentials to log in to the NZVH IPT. It is probably possible to store credentials in Jenkins, so it would be nice if we could do it in Jenkins instead of an external script, so that the job can be re-used for other private IPT data resources.

The only thing the external script did was downloading the IPT data set and putting it on the upload server. We might be able to skip the upload server.

**Comment by javier-molina** [comment]
This is superseded by https://github.com/AtlasOfLivingAustralia/preingestion/issues/34
