### ISSUE TITLE
Investigate why iNaturalist usernames are not coming across

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/data-management#775]
This could be a problem with pipelines. There is a field `<field index=“40” term=“http://xmlns.com/foaf/0.1/nick”>` in meta.xml coming across which seems to contain the iNaturalist username.

Find out why the username is not being ingested.

It should be indexed into the `alaUserId` or `userId` field (note: legacy `alau_user_id` should be mapped to one of those I think) which is the field used to link a user's profile to view iNat records in biocache.

**Comment by peggynewman** [comment]
iNaturalist are populating the recordedBy field, and not simply with an iNaturalist username or ID, but sometimes just with the name text. It's not pipelines that changed, it's changing the feed from using the iNaturalist API to harvest records that did it. When we used the API I think we got the user ID which easily forms a link to an iNaturalist profile. They don't send us this anymore - but they are sending recordedByID if they have someone's ORCID. See my record here: https://biocache.ala.org.au/occurrences/fbf95aae-f41e-416e-b3e2-9fcc3a9d1817

Maybe the solution is to ask iNaturalist to only populate recordedBy with the iNaturalist username or user ID (both of which are unique) or even the full url to their profile (eg https://www.inaturalist.org/people/peggydnew or https://www.inaturalist.org/people/708886)

**Comment by timhicks-ala** [comment]
Raised in:
https://support.ehelp.edu.au/a/tickets/121143
https://support.ehelp.edu.au/a/tickets/120539
https://support.ehelp.edu.au/a/tickets/123482

**Comment by nickdos** [comment]
@peggynewman I think this issue needs escalating... 8 support tickets waiting on it.

**Comment by peggynewman** [comment]
From iNaturalist:

> The extract contains a recordedBy field that either contains the inat user id or the user name, it seems, if it exists. We try to let users search for their records on the ALA by linking their iNaturalist account over OAUTH2 and retrieving their user id. We then give them a link that searches for the user id in the data. To this end, it would be better if the recordedBy field contained just the userID (ie, mine is peggydnew), for uniqueness, rather than the display name. Could you make that change to the extract?

Yes the recordedBy field will contain the user's preferred name if one exists, otherwise it will contain the user login/username (as you call it the user ID). There is another column for inaturalistLogin (mapped to http://xmlns.com/foaf/0.1/nick) which always contains just the user login which you should be able to use for iNaturalist account linking. Additionally there is a column recordedByID which contains the user ORCID if they have linked their ORCID account to their iNaturalist account. For anyone that has gone the extra step to link their iNaturalist account to ORCID, that globally unique ID would probably be the best way to map accounts. But for everyone else you should be able to use the user login in inaturalistLogin.

**Comment by cha801p** [comment]
-Login Username is populated on changing column name from **nick** to **userId** in meta.xml 
-Tested successfully on Databox

**Comment by peggynewman** [comment]
Deployed to prod today. Seems to be fixed.
