### ISSUE TITLE
Remove Weedscan test data

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/data-management#980]
Soft delete the Weedscan data asap
Disable the Weedscan schedule

Data resource: https://collections.ala.org.au/public/show/dr21567

Further discussions are needed on filtering and excluding private data

**Comment by cha801p** [comment]
**Ticket Update:** September 25, 2023 (5 PM)

**Issue Resolved:** 1. Soft delete the Weedscan data
2. Disable the Weedscan schedule

**Solution:** 1. We have successfully performed a soft delete operation on the Avro files for the following dataset: [dr21567](https://collections.ala.org.au/public/show/dr21567)
2. Regarding disabling the Weedscan schedule - https://github.com/AtlasOfLivingAustralia/preingestion/issues/195 
The ticket above implies that the job wasn't scheduled due to the absence of data updates from the data provider. Therefore, there is currently no requirement to deactivate the Weedscan schedule.

**Actions Taken:**
Executed the "Delete_dataset_dag" with the following parameters:
{ "datasetIds": "dr21567",
 "remove_records_in_solr": "true",
 "remove_records_in_es": "false",
 "delete_avro_files": "true",
 "retain_dwca": "true",
 "retain_uuid": "true" }

**Validation:** I have confirmed the following:

- [ ]  UUIDs have been preserved.
- [ ]  This action should not cause any issues in the upcoming indexing process.

**Comment by peggynewman** [comment]
Thanks Raj, we'll need to go through the steps to remove it from GBIF as well, as per [this issue](https://github.com/AtlasOfLivingAustralia/data-management/issues/947)

- [x] Retain the GBIF registry key: 49b9005f-5c8e-44fa-85ab-b6e1b030bbc7
- [x] Click 'Delete from GBIF'
- [x] Untick 'is shareable with GBIF'
- [x] Don't need to Set data resource to private

Done.
